### ISSUE TITLE
[BUG] - 

### ISSUE THREAD

**Issue by forma-pl** [lucasmonstrox/PyTibia#72]
**Describe the bug**
Cant run the main.py
[Python] 3.9.13 - installed
[Poetry]>=1.2.0 - installed

**Expected behavior**
PS C:\Users\Forma\Source\Repos\PyT> poetry run python main.py
Traceback (most recent call last):
  File "C:\Users\Forma\Source\Repos\PyT\main.py", line 116, in <module>
    main()
  File "C:\Users\Forma\Source\Repos\PyT\main.py", line 102, in main
    context = handleGameData(context)
  File "C:\Users\Forma\Source\Repos\PyT\main.py", line 41, in handleGameData
    context = setChatTabsMiddleware(context)
  File "C:\Users\Forma\Source\Repos\PyT\src\gameplay\core\middlewares\chat.py", line 7, in setChatTabsMiddleware
    context['chat']['tabs'] = getTabs(context['screenshot'])
  File "C:\Users\Forma\Source\Repos\PyT\src\repositories\chat\core.py", line 30, in getTabs
    x, y, width, height = leftSidebarArrowsPosition[1] + 18, chatMenuPosition[1], chatMenuPosition[1] - (leftSidebarArrowsPosition[1] + 18), 20
TypeError: 'NoneType' object is not subscriptable

**Screenshots**

**Desktop (please complete the following information):**

**Comment by eduardomottoni** [comment]
Same here,

I tried to run the command with the tibia logged in and get insta deleted, be careful

**Comment by fonciarz0** [comment]
has to be something with latest patch I guess, having the same error
