### ISSUE TITLE
[BUG] - error while starting application. any ideas?

### ISSUE THREAD

**Issue by Vallorlo** [lucasmonstrox/PyTibia#75]
I encountered this error while trying to run the application. I have poetry installed and also python. here's what my cmd says.

PyTibia-main>poetry run python main.py
Traceback (most recent call last):
  File "Desktop\PyTibia-main\main.py", line 2, in <module>
    from src.gameplay.threads.pyTibia import PyTibiaThread
  File "Desktop\PyTibia-main\src\gameplay\threads\pyTibia.py", line 12, in <module>
    from src.gameplay.core.middlewares.window import setTibiaWindowMiddleware
  File "Desktop\PyTibia-main\src\gameplay\core\middlewares\window.py", line 2, in <module>
    import win32gui
ModuleNotFoundError: No module named 'win32gui'

--------------------------------------------------------------------------------------------------------

keep in mind I have pywin32 already installed. idk what to do from here. I already did the command poetry install too.

**Comment by mateuszk131** [comment]
I had similar with win32con import, how i fixed it:
pip install pywin32
Copy pywin32 folder and pywin32.pth from C:\Users\XXX\AppData\Local\Programs\Python\Python39\  
to
C:\Users\Mateusz\AppData\Local\pypoetry\Cache\virtualenvs\pytibia-yRHMxwev-py3.9\Lib\site-packages

**Comment by lucasmonstrox** [comment]
@mateuszk131 can you open PR with your fix?

**Comment by felipetnh** [comment]
If I understood correctly, there won't be a PR, because the fix wasn't on the code, it was actually on poetry virtualenvs. He just copied the pywin32 folder and files from one place to another.
