### ISSUE TITLE
help

### ISSUE THREAD

**Issue by vatxz** [lucasmonstrox/PyTibia#87]
hello
someone can share a video how to run it?

i got all the requeriments and the interface how as guide
but i dont have idea why is not working

when i run poetry run python -m pytest

i got

C:\Users\sanga\Appata\Local\pypoetry\Cache\virtualenvs\pytibia-1gKz31sh-py3.11\Scripts\pthon.exe: No module named pytest

**Comment by lutiqhas** [comment]
C:\Users\lucas\Tibia\PyTibia-main>poetry run python main.py
Creating virtualenv pytibia-6t_xH0zf-py3.11 in C:\Users\lucas\AppData\Local\pypoetry\Cache\virtualenvs
Traceback (most recent call last):
  File "C:\Users\lucas\Tibia\PyTibia-main\main.py", line 2, in <module>
    from src.gameplay.threads.pyTibia import PyTibiaThread
  File "C:\Users\lucas\Tibia\PyTibia-main\src\gameplay\threads\pyTibia.py", line 1, in <module>
    import pyautogui
ModuleNotFoundError: No module named 'pyautogui'
