### ISSUE TITLE
[BUG] - starting issue

### ISSUE THREAD

**Issue by TIBIA98** [lucasmonstrox/PyTibia#93]
poetry run python main.py
Traceback (most recent call last):
  File "D:\downloads\PyTibia-main\main.py", line 2, in <module>
    from src.gameplay.threads.pyTibia import PyTibiaThread
  File "D:\downloads\PyTibia-main\src\gameplay\threads\pyTibia.py", line 4, in <module>
    from src.gameplay.cavebot import resolveCavebotTasks, shouldAskForCavebotTasks
  File "D:\downloads\PyTibia-main\src\gameplay\cavebot.py", line 2, in <module>
    from src.repositories.gameWindow.creatures import hasTargetToCreature
  File "D:\downloads\PyTibia-main\src\repositories\gameWindow\creatures.py", line 8, in <module>
    from src.repositories.radar.config import walkableFloorsSqms
  File "D:\downloads\PyTibia-main\src\repositories\radar\config.py", line 86, in <module>
    floorsPathsSqms = np.load(f'{currentPath}/npys/floorsPathsSqms.npy')
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\GRNX\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\Local\pypoetry\Cache\virtualenvs\pytibia-TlZ42Pqm-py3.11\Lib\site-packages\numpy\lib\npyio.py", line 427, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))

FileNotFoundError: [Errno 2] No such file or directory: 'D:\\downloads\\PyTibia-main\\src\\repositories\\radar/npys/floorsPathsSqms.npy'

**Comment by TIBIA98** [comment]
ok i managed to start bot, setup client like in tutorial but nothing works, also got tons of this error in console 
An exception occurred: Traceback (most recent call last):
  File "D:\downloads\PyTibia-main\src\gameplay\threads\pyTibia.py", line 39, in mainloop
    self.context.context = self.handleGameData(
                           ^^^^^^^^^^^^^^^^^^^^
  File "D:\downloads\PyTibia-main\src\gameplay\threads\pyTibia.py", line 66, in handleGameData
    context = setDirectionMiddleware(context)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\downloads\PyTibia-main\src\gameplay\core\middlewares\gameWindow.py", line 15, in setDirectionMiddleware
    if context['radar']['coordinate'][0] != context['radar']['previousCoordinate'][0] or context['radar']['coordinate'][1] != context['radar']['previousCoordinate'][1] or context['radar']['coordinate'][2] != context['radar']['previousCoordinate'][2]:
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
TypeError: 'NoneType' object is not subscriptable

**Comment by maximiliannm** [comment]
how did you solve f'{currentPath}/npys/floorsPathsSqms.npy')  error and start bot?

**Comment by Feliipe93** [comment]
dir "C:\Users\felip\Downloads\PyTibia-main\src\repositories\radar\npys\floorsPathsSqms.npy"

**Comment by matheusbristot** [comment]
The file was deleted on ~HEAD commit. Please unpack the zip file and use it.

[floorsPathsSqms.npy.zip](https://github.com/user-attachments/files/24983858/floorsPathsSqms.npy.zip)
