### ISSUE TITLE
[BUG] - ERROR INSTALATION 

### ISSUE THREAD

**Issue by TheMachineplus** [lucasmonstrox/PyTibia#95]
PS C:\Users\XTREME\Downloads\PyTibia-main> poetry run python main.py
Traceback (most recent call last):
  File "C:\Users\XTREME\Downloads\PyTibia-main\main.py", line 2, in <module>
    from src.gameplay.threads.pyTibia import PyTibiaThread
  File "C:\Users\XTREME\Downloads\PyTibia-main\src\gameplay\threads\pyTibia.py", line 4, in <module>
    from src.gameplay.cavebot import resolveCavebotTasks, shouldAskForCavebotTasks
  File "C:\Users\XTREME\Downloads\PyTibia-main\src\gameplay\cavebot.py", line 2, in <module>
    from src.repositories.gameWindow.creatures import hasTargetToCreature
  File "C:\Users\XTREME\Downloads\PyTibia-main\src\repositories\gameWindow\creatures.py", line 8, in <module>
    from src.repositories.radar.config import walkableFloorsSqms
  File "C:\Users\XTREME\Downloads\PyTibia-main\src\repositories\radar\config.py", line 86, in <module>
    floorsPathsSqms = np.load(f'{currentPath}/npys/floorsPathsSqms.npy')
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XTREME\AppData\Local\pypoetry\Cache\virtualenvs\pytibia-ACqiDWIs-py3.11\Lib\site-packages\numpy\lib\npyio.py", line 427, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\XTREME\\Downloads\\PyTibia-main\\src\\repositories\\radar/npys/floorsPathsSqms.npy'
PS C:\Users\XTREME\Downloads\PyTibia-main>

**Comment by Maxosanso** [comment]
dead thread
